import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <img className="fixed w-full -z-10 object-cover max-h-screen " alt='frogo' src='/frogbg.png'/>
      {children}
      </body>

    </html>
  );
}
